platform :ios, '14.1'

target 'JSONAPIExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JSONAPIExample
  pod 'Alamofire'
  pod 'SwiftyJSON'
end
