# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'RxSwiftTestProj' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftTestProj
  pod 'CWUtils'
  pod 'SwiftyJSON'

end
